### ISSUE TITLE
ideas

### ISSUE THREAD

**Issue by ZakariaAitAli** [FixedInteger/cpp-essentialTraining#2]
### Discussed in https://github.com/orgs/FixedInteger/discussions/1

<div type='discussions-op-text'>

<sup>Originally posted by **eddahbihossine** October 10, 2023</sup>
hiii</div>

**Comment by eddahbihossine** [comment]
it 's done

**Comment by ZakariaAitAli** [comment]
https://github.com/FixedInteger/cpp-essentialTraining/issues/2#issuecomment-1754058394
